app.service('Lang', ["$sce", function($sce) {
   var _lang = "english",
   _langs = [
      {
        "id" : "english",
        "label" : "English",
        "credit" : ""
      }
    ],
    _translations = {
      "english" : {
        "error_please_enter_your_seed_words" : "Please enter your seed words",
        "error_seed_words_not_valid" : "Your seed words are not valid - please check to ensure you are not missing a word/letter, and you haven't included an extra space/line break. All words must be seperated by a space.",
        "error_enter_passphrase" : "Please enter your passphrase",
        "error_enter_email" : "Please enter your email from the ICO PDF",
        "error_enter_address" : "Please enter your address/Public Key Hash from the ICO PDF",
        "error_enter_private_key" : "Please enter your private key",
        "error_enter_encryption_password" : "Please enter the encryption password for your edesk private key",
        "error_fundraiser_details_dont_mach" : "Your fundraiser details don't seem to match - please try again and ensure you are entering your details in correctly. The most common issue is an incorrect password.",
        "error_import_encrypted" : "There was an issue trying to import your encrypted key, please try again.",
        "error_enter_password" : "Please enter your password",
        "error_password_short" : "Your password is too short",
        "error_password_dont_match" : "Passwords do not match",
        "error_password_spaces" : "Your password can't include any spaces",
        "error_password_upper_lower" : "Please include at least one uppercase and lowercase letter in your password",
        "error_password_special" : "Please include at least one special character (number or symbol) in your password",
        "error_path_ledger" : "Please enter your address path for your Ledger",
        "error_path_trezor" : "Please enter your address path for your Trezor",
        "error_offline_address" : "Please enter the tz address to observe",
        "error_new_title" : "Please enter a new title",
        "error_kt1_address" : "Please enter the KT1 address to import",
        "error_kt1_linked" : "That address is already linked to your wallet!",
        "error_kt1_manager" : "That account is not managed by your account key",
        "error_importing" : "There was an error importing that account",
        "error_undeveloped" : "You seem to be using a signing method that has not been developed yet!",
        "error_origination_awaiting" : "Error: awaiting existing origination to activate",
        "error_valid_destinaton" : "Please enter a valid Destination Address",
        "error_send_self" : "You can't send to yourself - please select another Destination Address",
        "error_positive_amount" : "Invalid amount entered - please enter a positive number",
        "error_amount_exceeds" : "The amount you entered exceeds the current balance for this account. Manager addresses (those that start with tz) must leave at least 0.000001 tez behind. You also need to take into account the fee you are using",
        "error_positive_fee" : "Invalid fee entered - please enter a positive number",
        "error_invalid_amount" : "Invalid amount entered - please enter a valid number",
        "error_invalid_fee" : "Invalid fee entered - please enter a valid number",
        "error_valid_delegate" : "Please enter or a valid delegate",
        "awesome" : "Awesome!",
        "uh_oh" : "Uh-oh!",
        "are_you_sure" : "Are you sure?",
        "secure_tezos_wallet" : "Secure Tezos Wallet",
        "welcome_back" : "Welcome Back!",
        "create_tezbox" : "Create TezBox",
        "restore" : "Restore",
        "link" : "Link your TezBox",
        "link_hardware_wallet" : "Do you want to link a Hardware Wallet?",
        "i_accept" : "I Accept",
        "i_accept_terms_conditions" : "I have Accepted the <a href=\"https://tezbox.com/terms.html\" target=\"_blank\">Terms</a> and <a href=\"https://tezbox.com/privacy.html\" target=\"_blank\">Privacy Policy</a>",
        "create_your_tezbox" : "Create your TezBox",
        "new_mnemonic" : "New Mnemonic",
        "continue" : "Continue",
        "cancel" : "Cancel",
        "validate_your_tezbox" : "Validate your TezBox",
        "secure_your_tezbox" : "Secure Your TezBox",
        "encrypt_wallet" : "Encrypt Wallet",
        "link_your_tezbox" : "Link your TezBox",
        "link_tezbox" : "Link Tezbox",
        "unlock_wallet" : "Unlock Wallet",
        "clear_tezbox" : "Clear TezBox",
        "back" : "Back",
        "show" : "Show",
        "hide" : "Hide",
        "seed_words_mnenomic" : "Seed Words/Mnenomic (leave a space between each word)",
        "seed_words_mnenomic_placeholder" : "Enter Seed Words",
        "optional_passphrase" : "Optional Passphrase",
        "optional_passphrase_tooltip" : "The optional passphrase will add an additional layer of security to your private key, and will also need to used to restore your account (so write this down as well). This is not the same as an encryption password.",
        "optional_passphrase_tooltip2" : "If no passphrase was set, just leave this blank",
        "password" : "Password",
        "password_tooltip2" : "Your password needs to be at least 8 characters long, and include at least one lowercase, one uppercase, and one special character (numeric or symbol), and must not contain blank spaces.",
        "password_again" : "Repeat Password",
        "hd_derivation_path" : "HD Derivation Path",
        "address" : "Address",
        "enter_password" : "Enter Password",
        "enter_password_to_show" : "Enter your password to show",
        "rpc_address" : "RPC Address",
        "ledger" : "Ledger",
        "trezor" : "Trezor",
        "offline_signer" : "Offline Signer",
        "trezor_coming_soon" : "Trezor support coming soon...",
        "warning" : "Be warned that you are dealing with the mainnet, which is a LIVE NETWORK. All transactions on this network are final.",
        "create_info" : "Please write your seed words below and store them in a secure place. These can be used to restore your wallet. If you choose to use a Passphrase, this will need to be noted down and stored as well",
        "validate_info" : "Please re-enter your seed words and passphrase in full from the previous step. This is to confirm that you have correctly recorded these down.",
        "secure_your_tezbox_info" : "Please enter a password to encrypt your private data. This password is only used to unlock your wallet (not required to restore it).",
        "ledger_info" : "Currently only the Ledger Nano S is supported - please also ensure the Tezos Wallet app has been setup on your Ledger and is currently open.",
        "trezor_info" : "Currently only the Trezor T is supported - please also ensure the firmware one your Trezor T has been updated to at least 2.0.8, and is plugged in and unlocked.",
        "hd_derivation_path_info" : "Advanced option to access different addresses - leave as it is to use the default key",
        "offline_signer_info" : "This method is effectively a view-only wallet. You can use an offline signing tool (an official TezBox tool is currently being developed).",
        "tezbox_settings_info" : "Please be careful with changing or interacting with these settings.",
        "export_private_key_info" : "Please be careful with this option, as anyone viewing your screen will see the private key below",
        "rpc_address_info" : "When running your own node, you can use your IP/domain here to connect to it by default. This needs to be available via SSL (HTTPS) to work with this wallet.",
        "tezbox_settings" : "TezBox Settings",
        "restore_your_tezbox" : "Restore your TezBox",
        "export_private_key" : "Export Private Key",
        "ico_fundraiser_wallet" : "ICO/Fundraiser Wallet",
        "seed_phrase" : "Seed Phrase",
        "private_key" : "Private Key",
        "ico_fundraiser_wallet_info" : "If you have a Fundraiser/ICO wallet, you must use this option everytime to restore your wallet. Please enter your seed words, email address, password and address/public key hash from the Fundraiser PDF. If your account has not been activated, please enter the activation code below as well.",
        "15_word_secret_key" : "15 Word Secret Key/Seed (leave a space between each word)",
        "email" : "Email",
        "email_tooltip" : "From the Fundraiser PDF, must be entered in exactly",
        "password_tooltip" : "This is the password you entered when you contributed to the ICO/Fundraiser. This may not be the same password as the account you created to complete KYC, and is not recorded on the Fundraiser PDF.",
        "public_key_hash" : "Public Key Hash",
        "public_key_hash_tooltip" : "From the Fundraiser PDF, must be entered in exactly",
        "activation_code" : "Activation Code",
        "activation_code_tooltip" : "Only enter if you haven't already activated your account",
        "seed_phrase_info" : "Please enter your seed and passphrase below and we will attempt to restore your wallet. If you are trying to restore your Fundraiser/ICO wallet please select the 'Fundraiser Wallet' tab instead (even if you have restored it previously)",
        "private_key_info" : "Please enter your private key and we will attempt to restore your wallet. This option is for those users who have exported a private key from the Tezos client (or have generated one elsewhere). Currently we only accept the \"edsk...\" and the \"edesk...\" variants. You will need to enter your encryption password if you are trying to import an encrypted private key (\"edesk..\")",
        "private_key_tooltip" : "Your private key can be exported from the Tezos Client or other wallets, and will start with edesk or edsk",
        "encryption_password" : "Encryption Password",
        "encryption_password_tooltip" : "This is the password used in the Tezos Client to encrypt your private key",
        "restore_tezbox" : "Restore TezBox",
        "activation_successful" : "Activation was successful - please keep in mind that it may take a few minutes for your balance to show!",
        "activation_unsuccessful" : "Activation was unsuccessful - please ensure the code is right, or leave it blank if you have already activated your account!",
        "restoring" : "Restoring...",
        "linking" : "Linking...",
        "ledger_confirm_transaction" : "Please confirm the transaction on your Ledger Nano S Device",
        "trezor_confirm_transaction" : "Please confirm the transaction on your Trezor T Device",
        "ledger_verify_address" : "Please verify the address on your Ledger Nano S Device",
        "trezor_verify_address" : "Please verify the address on your Trezor T Device",
        "ledger_retreived_address" : "We have retreived the following address from your hardware wallet",
        "ledger_error_connect" : "There was an issue connecting to your hardware wallet. Please ensure your device is connected, and the Tezos Wallet app is selected.",
        "ledger_error_signing" : "There was an error signing this operation with your Ledger",
        "details_dont_match" : "Sorry, those details do not match - please try again, or go back and create a new account again",
        "please_enter_password" : "Please enter your password",
        "incorrect_password" : "Incorrect password",
        "clear_tezbox_warning" : "You are about to clear you TezBox - note, unless you've backed up your seed words or private key you'll no longer have access to your accounts",
        "yes_clear_it" : "Yes, clear it!",
        "my_accounts" : "My Accounts",
        "add_account" : "Add Account",
        "level" : "level",
        "disclaimer" : "Disclaimer",
        "terms" : "Terms",
        "privacy" : "Privacy",
        "view_on_tzscan" : "View on TzScan",
        "account_notadded" : "This account has not been added to the blockchain yet - please wait for a baker to include this in a block before you can use this account. This error may also show if your device can't connect to the Tezos Network.",
        "transactions" : "Transactions",
        "send" : "Send",
        "delegate" : "Delegate",
        "options" : "Options",
        "no_transactions" : "No transactions available",
        "received" : "RECEIVED",
        "sent" : "SENT",
        "from" : "From",
        "to" : "To",
        "last_20_transactions" : "Only the last 20 transactions are being displayed.",
        "view_more_here" : "View more here",
        "destination_address" : "Destination Address",
        "destination_tooltip" : "This is the address you want to send to - please enter a valid KT1 or tz address",
        "enter_address" : "Enter Address",
        "amount" : "Amount",
        "amount_tooltip" : "Please enter an amount in tez. When sending from a tz address, you must leave at least 0.000001 behind",
        "max" : "Max",
        "fee" : "Fee",
        "fee_tooltip" : "This is the total fee to paid for the transaction. Currently 0 tez fees are accepted.",
        "custom_fee" : "Custom Fee",
        "fee_options" : "Fee Options",
        "no_fee" : "No Fee",
        "low" : "Low",
        "medium" : "Medium",
        "high" : "High",
        "show_advanced_options" : "Show Advanced Options",
        "hide_advanced_options" : "Hide Advanced Options",
        "parameters" : "Parameters",
        "parameters_tooltip" : "Optional parameters to send as input - this is only required for some smart contracts.",
        "gas_limit" : "Gas Limit",
        "gas_limit_tooltip" : "Set the gas limit for this operations. For simple transactions, you can leave this as the default",
        "storage_limit" : "Storage Limit",
        "storage_limit_tooltip" : "Set the storage limit for this operations. For simple transactions, you can leave this as the default",
        "clear" : "Clear",
        "ensure_delegate" : "Please ensure the delegate you are entering has been registered to participate in the baking protocol.",
        "endorse_delegate" : "TezBox doesn't endorse any of the listed delegation services listed below - please ensure you are doing your own research into each one.",
        "disabled_delegate" : "Delegation from this address is not allowed (lowercase tz addresses) - these are referred to as implicit addresses and the protocol doesn't allow them to delegate to another key. Please create an account (KT address) to use for delegation.",
        "delegate_options" : "Delegate Options",
        "delegate_options_tooltip" : "Delegate your account to participate in the baking process. Select a pre-set baker, or enter your own",
        "custom_delegate" : "Custom Delegate",
        "custom_delegate_tooltip" : "Enter your custom delegate address here - it must start with tz...",
        "update_delegate" : "Update Delegate",
        "title" : "Title",
        "update_title" : "Update Title",
        "import_kt1_account" : "Import KT1 Account",
        "import_kt1_account_msg" : "You can use this to import KT1 addresses that have been originated else where (or after you have restored your account). You can view all of your originated KT1 addresses on",
        "import" : "Import",
        "remove_account" : "Remove Account",
        "connected_to" : "Connected to",
        "not_connected" : "Not Connected",        
        "remove_account_warning" : "You are about to remove this account from your wallet! (You can always restore this account in future by going to Options > Import)",
        "yes_remove_it" : "Yes, remove it!",
        "originate_warning" : "Creating a new account incurs an origination fee of ~0.257 XTZ. Do you want to continue?)",
        "yes_continue" : "Yes, continue!",
        "new_account_originated" : "Your new account has been originated - this may take a few minutes to be included on the blockchain",
        "origination_error" : "There was an error adding account. Please ensure your main account has funds available",
        "loading" : "Loading...",
        "copy_clipboard" : "The address has been copied to your clipboard",
        "yes_send_it" : "Yes, send it!",
        "transaction_sent" : "Transaction has been sent - this may take a few minutes to be included on the blockchain",
        "operation_failed" : "Operation Failed!",
        "operation_failed2" : "Operation Failed! Please check your inputs",
        "delegation_success" : "Delegation operation was successful - this may take a few minutes to update",
        "delegation_failed" : "Delegation Failed",
        "import_kt_address" : "Import KT addresses",
        "import_kt_address_info" : "We have found $$ KT1 address(es) linked to your public key - would you like to import them now? (You can also manually import these by going to Options > Import)",
        "yes_import_them" : "Yes, import them!",
        "ico_restore_success" : "You have successfully restored your ICO wallet. If you have just activated your account, please note that this may take some time to show.",
        "transaction_confirm_info" : "You are about to send $$XTZ to $$ - this transaction is irreversible",
      }

    },
    r = {};
    r.setLang = function(l){
        _lang = l;
    };
    r.getLangs = _langs;
    r.translate = function(id, rep){
      if (typeof rep != 'undefined' && typeof _translations[_lang][id] != 'undefined'){
        var tt = _translations[_lang][id];
        for(var i = 0; i < rep.length; i++){
          tt = tt.replace("$$", rep[i]);
        }
        return tt;
      } else return (typeof _translations[_lang][id] != 'undefined' ? _translations[_lang][id] : _lang + "." + id);
    };
    return r;
}]);
